name: Build & Test React Application

on:
  push:
    branches: ["frontend"]
  pull_request:
    branches: ["frontend"]

env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  REACT_APP_GOOGLE_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_GOOGLE_RECAPTCHA_SITE_KEY }}
  REACT_APP_GOOGLE_RECAPTCHA_SECRET_KEY: ${{ secrets.REACT_APP_GOOGLE_RECAPTCHA_SECRET_KEY }}
  REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Git Config
        run: |
          git config user.name "Stephen Phyo"
          git config user.email "stephenphyo2019.official@gmail.com"

      - name: Install Dependencies
        run: npm install

      - name: Build React Project
        run: |
          npm run build --if-present
        env:
          CI: false

      - name: Save Version
        id: version
        run: echo ::set-output name=tag

      - name: Login to DockerHub Registry
        run: echo ${{  secrets.DOCKER_PASSWORD }} | docker login -u ${{  secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build --file Dockerfile.prod --tag stephenphyo/web-005-spaceshare-frontend:prod1.01 .

      - name: Push to Docker Hub Repository
        run: docker push stephenphyo/web-005-spaceshare-frontend:prod1.01
